# Generated by Django 2.1.7 on 2020-03-06 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0002_property_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='values',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rent_data.Value'),
        ),
    ]
