# Generated by Django 2.1.7 on 2020-03-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0004_auto_20200305_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='section_8',
            field=models.BooleanField(default=False),
        ),
    ]
