# Generated by Django 2.1.7 on 2020-03-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0005_property_section_8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
