# Generated by Django 2.1.7 on 2020-03-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0006_auto_20200306_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
