# Generated by Django 2.1.7 on 2020-03-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0007_property_year_built'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentobservation',
            name='year',
        ),
        migrations.AddField(
            model_name='rentobservation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
