# Generated by Django 2.1.7 on 2020-03-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0010_auto_20200307_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lease_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
