# Generated by Django 2.1.7 on 2020-03-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0011_property_lease_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementobservation',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
