# Generated by Django 2.1.7 on 2020-03-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0014_remove_policereport_incident_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EMSReport',
        ),
        migrations.RemoveField(
            model_name='firereport',
            name='address',
        ),
        migrations.RemoveField(
            model_name='firereport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='firereport',
            name='longitude',
        ),
        migrations.AddField(
            model_name='firereport',
            name='ems',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='fire_reports',
            field=models.ManyToManyField(to='rent_data.FireReport'),
        ),
    ]
