# Generated by Django 2.1.7 on 2020-03-06 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='values',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rent_data.Value'),
            preserve_default=False,
        ),
    ]
