# Generated by Django 2.1.7 on 2020-03-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0003_auto_20200305_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='values',
        ),
        migrations.AddField(
            model_name='property',
            name='values',
            field=models.ManyToManyField(to='rent_data.Value'),
        ),
    ]
