# Generated by Django 2.1.7 on 2020-03-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0008_auto_20200307_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='act_ally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
