# Generated by Django 2.1.7 on 2020-03-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0009_auto_20200307_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rentobservation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='management_companies',
            field=models.ManyToManyField(to='rent_data.ManagementObservation'),
        ),
    ]
