# Generated by Django 2.1.7 on 2020-03-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0012_auto_20200307_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policereport',
            name='address',
        ),
        migrations.RemoveField(
            model_name='policereport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='policereport',
            name='longitude',
        ),
        migrations.AddField(
            model_name='property',
            name='police_reports',
            field=models.ManyToManyField(to='rent_data.PoliceReport'),
        ),
    ]
