# Generated by Django 2.1.7 on 2020-06-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0015_auto_20200317_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='year',
        ),
    ]
