# Generated by Django 3.0.7 on 2020-07-09 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0016_remove_stat_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvictionDisposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Eviction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(default='', max_length=255)),
                ('date', models.DateTimeField(null=True)),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_data.EvictionDisposition')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='evictions',
            field=models.ManyToManyField(to='rent_data.Eviction'),
        ),
    ]
