# Generated by Django 3.0.7 on 2020-07-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_data', '0019_auto_20200709_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eviction',
            name='id',
        ),
        migrations.AlterField(
            model_name='eviction',
            name='case_number',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
